[target.x86_64-unknown-uefi]
runner = "scripts/cargo-uefi-runner.sh"

[target.x86_64-tetsu-kernel]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]

[alias]
uefi = "run -p tetsu-boot --target x86_64-unknown-uefi"
build-boot = "build -p tetsu-boot --target x86_64-unknown-uefi"
test-boot = "test -p tetsu-boot-tests --target x86_64-unknown-uefi"