[target.x86_64-unknown-uefi]
runner = "scripts/cargo-uefi-runner.sh"

[target.x86_64-tetsu-kernel]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]
runner = "scripts/cargo-kernel-runner.sh"

[alias]
uefi = "run -p tetsu-boot --target x86_64-unknown-uefi"
kernel = "run -p tetsu-kernel -Zjson-target-spec  -Z build-std=core -Z build-std-features=compiler-builtins-mem --target tetsu-kernel/x86_64-tetsu-kernel.json"
build-boot = "build -p tetsu-boot --target x86_64-unknown-uefi"
test-boot = "test -p tetsu-boot-tests --target x86_64-unknown-uefi"
build-kernel = "build -p tetsu-kernel -Zjson-target-spec  -Z build-std=core -Z build-std-features=compiler-builtins-mem --target tetsu-kernel/x86_64-tetsu-kernel.json"
test-kernel = "test -p tetsu-kernel-tests -Zjson-target-spec  -Z build-std=core -Z build-std-features=compiler-builtins-mem --target tetsu-kernel/x86_64-tetsu-kernel.json"
