name: tetsu-tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [check, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure scripts are executable
        run: chmod +x scripts/*.sh

      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: abi

      - name: Build tetsu-abi library
        run: cargo +nightly build -p tetsu-abi

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: abi-check

      - name: Cargo check
        run: cargo +nightly check -p tetsu-abi


  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust nightly (clippy)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: abi-clippy

      - name: Clippy
        run: cargo +nightly clippy -p tetsu-abi -- -D warnings
