name: tetsu
on:
  push:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust nightly (rustfmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: fmt

      - name: Rustfmt (workspace)
        run: cargo +nightly fmt --all -- --check

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: audit

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: cargo audit
        run: cargo audit --deny warnings

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deny

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: cargo deny check
        run: cargo deny check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: typos
        uses: crate-ci/typos@v1.24.6
